In [2]:
from numpy import zeros,array
import numpy

In [3]:
def tri_selection(tableau):
    nb = len(tableau)
    for en_cours in range(0,nb):    
        plus_petit = en_cours
        for j in range(en_cours+1,nb) :
            if tableau[j] < tableau[plus_petit] :
                plus_petit = j
        if min is not en_cours :
            temp = tableau[en_cours]
            tableau[en_cours] = tableau[plus_petit]
            tableau[plus_petit] = temp
    return tableau

In [4]:
tableau = numpy.random.randint(0,10,size=10)
tri_selection(tableau)

array([0, 4, 5, 6, 7, 9, 9, 9, 9, 9])

In [5]:
def tri_bulle(tableau):
    permutation = True
    passage = 0
    while permutation == True:
        permutation = False
        passage = passage + 1
        for en_cours in range(0, len(tableau) - passage):
            if tableau[en_cours] > tableau[en_cours + 1]:
                permutation = True
                # On echange les deux elements
                tableau[en_cours], tableau[en_cours + 1] = \
                tableau[en_cours + 1],tableau[en_cours]
    return tableau  

In [6]:
tableau = numpy.random.randint(0,10,size=10)
tri_bulle(tableau)

array([0, 0, 2, 4, 4, 4, 5, 6, 7, 8])

In [7]:
def tri_insertion(tableau):
    for i in range(1,len(tableau)):
        en_cours = tableau[i]
        j = i
        #décalage des éléments du tableau }
        while j>0 and tableau[j-1]>en_cours:
            tableau[j]=tableau[j-1]
            j = j-1
        #on insère l'élément à sa place
        tableau[j]=en_cours
    return tableau

In [8]:
tableau = numpy.random.randint(0,10,size=10)
tri_insertion(tableau)

array([0, 1, 3, 4, 4, 4, 5, 7, 7, 9])

In [9]:
def fusion(gauche,droite):
    resultat = []
    index_gauche, index_droite = 0, 0
    while index_gauche < len(gauche) and index_droite < len(droite):        
        if gauche[index_gauche] <= droite[index_droite]:
            resultat.append(gauche[index_gauche])
            index_gauche += 1
        else:
            resultat.append(droite[index_droite])
            index_droite += 1
    if gauche:
        resultat.extend(gauche[index_gauche:])
    if droite:
        resultat.extend(droite[index_droite:])
    return resultat
 
def tri_fusion(m):
    if len(m) <= 1:
        return m
    milieu = len(m) // 2
    gauche = m[:milieu]
    droite = m[milieu:]
    gauche = tri_fusion(gauche)
    droite = tri_fusion(droite)
    return list(fusion(gauche, droite))

In [10]:
tableau = numpy.random.randint(0,10,size=10)
tri_fusion(tableau)

[0, 1, 2, 2, 3, 4, 4, 5, 7, 7]

In [11]:
def tri_rapide(t):
    if t == []:
        return []
    else:
        pivot = t[0]
        t1 = []
        t2 = []
    for x in t[1:]:
        if x<pivot:
            t1.append(x)
        else:
            t2.append(x)
    return tri_rapide(t1)+[pivot]+tri_rapide(t2)


In [12]:
tableau = numpy.random.randint(0,10,size=10)
tri_rapide(tableau)

<ipython-input-11-fcc77b81c130>:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if t == []:


[1, 2, 3, 3, 5, 5, 7, 7, 7, 8]

In [13]:
import time
import numpy

In [14]:
def temps_insertion(N):
    n=100
    t1 =time.time()
    for k in range(n):
        liste = numpy.random.randint(0,N,size=N)
        tri_insertion(liste)
    t1 = time.time()-t1
    return t1

In [15]:
temps_insertion(10)

0.008867025375366211

In [16]:
M=[50, 100]#, 3000, 4000, 5000, 6000]
z=[]
for i in M:
    z.append(temps_insertion(i))
print(z)    

[0.1319434642791748, 0.48674845695495605]


In [17]:
def temps_selection(N):
    n=100
    t1 =time.time()
    for k in range(n):
        liste = numpy.random.randint(0,N,size=N)
        tri_selection(liste)
    t1 = time.time()-t1
    return t1

In [18]:
def temps_bulle(N):
    n=100
    t1 =time.time()
    for k in range(n):
        liste = numpy.random.randint(0,N,size=N)
        tri_bulle(liste)
    t1 = time.time()-t1
    return t1

In [19]:
 def temps_fusion(N):
    n=100
    t1 =time.time()
    for k in range(n):
        liste = numpy.random.randint(0,N,size=N)
        tri_fusion(liste)
    t1 = time.time()-t1
    return t1

In [20]:
def temps_rapide(N):
    n=100
    t1 =time.time()
    for k in range(n):
        liste = numpy.random.randint(0,N,size=N)
        tri_rapide(liste)
    t1 = time.time()-t1
    return t1

In [ ]:
M=[50, 100, 1000, 2000, 4000, 5000]#, 3000, 4000, 5000, 6000]
ins=[]
selc=[]
rap=[]
fusi=[]
bulle=[]
for i in M:
    ins.append(temps_insertion(i))
    selc.append(temps_selection(i))
    rap.append(temps_rapide(i))
    fusi.append(temps_fusion(i))
    bulle.append(temps_bulle(i))
print(ins)
print(selc)
print(rap)
print(fusi)
print(bulle)


<ipython-input-11-fcc77b81c130>:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if t == []:


In [1]:
import matplotlib.pyplot as plt
y_selection=selc
y_insertion=ins
y_bulle=bulle
y_rapid=rap
y_fusion=fusi
plt.plot(M,y_selection,label='tri_de_selection')
plt.plot(M,y_insertion,label='tri_dinsertion')
plt.plot(M,y_bulle,label="tri abulle")
plt.plot(M,y_rapid,label="tri rapide")
plt.plot(M,y_fusion,label="tri de fusion")
plt.xlabel("la complexité N")
plt.ylabel("temps")
plt.legend()
plt.show()

NameError: name 'selc' is not defined